### ISSUE TITLE
Surface::Pixels() may return an undersized slice

### ISSUE THREAD

**Issue by manuelmenzella** [veandco/go-sdl2#480] opened 2021-04-27 02:53 UTC
`Surface::Pixels()` [calculates](https://github.com/veandco/go-sdl2/blob/master/sdl/surface.go#L542) the length of the underlying buffer as `width * heigh * bytesPerPixel`. However, the pitch (i.e. bytes per row) is not always `width * bytesPerPixel`. More concretely, it is [rounded up](https://github.com/libsdl-org/SDL/blob/c59d4dcd38c382a1e9b69b053756f1139a861574/src/video/SDL_surface.c#L51) to a multiple of four.

This probably slipped through the cracks because, usually, either `bytesPerPixel` is four or `width` is a multiple of four, which makes this a non-issue.

I propose modifying `Surface::Pixels()` to expose the whole buffer. Unfortunately, this means that the returned slice will contain some bytes that are ignored. A better name for this function would be `Surface::Buffer` or perhaps `Surface::Data`.

**Comment by veeableful** [comment] 2021-04-28 12:14
Hi @manuelmenzella, I think you are right that we should probably change the slice length calculation code, perhaps to `height * pitch`? I will try to produce an example that shows the issue with the current code so I know we fixed some cases with that change sometime this weekend (unless you already have an existing example to show in which case I would love to see it!).

**Comment by manuelmenzella** [comment] 2021-05-01 04:05
Thanks for looking into this! I had a busy last couple of days, but I’ll create a minimal example tomorrow and share it here.

**Comment by veeableful** [comment] 2021-05-01 07:37
Thank you, that would be very helpful!

**Comment by manuelmenzella** [comment] 2021-05-01 22:49
Hi @veeableful; I've added a minimal reproducible example [here](https://github.com/manuelmenzella/sdl2-buffer-bug/blob/main/main.go). You should be able to run `go build` and run the executable -- see the comments in the code for details. Let me know if you have any questions!

I've confirmed that replacing `surface.W` with `surface.Pitch` where the [slice length is calculated](https://github.com/veandco/go-sdl2/blob/c3fc9cecf2388316154a48fc041cf054f92fa5de/sdl/surface.go#L542) fixes the issue.

**Comment by veeableful** [comment] 2021-05-02 04:48
Thank you very much for your time in creating the example @manuelmenzella! I have confirmed that the change fixes the issue. I have tagged the commit so you should be able to apply the fix by updating version of go-sdl2 in the`go.mod` file to `v0.4.6` 🙂

P.S. I had to modify a line in the example code to `buf[len(buf)-4] = 0xff` for setting the last pixel to blue as I suppose the last three bytes of each line are unused because of padding.

**Comment by manuelmenzella** [comment] 2021-05-02 13:52
> P.S. I had to modify a line in the example code to buf[len(buf)-4] = 0xff for setting the last pixel to blue as I suppose the last three bytes of each line are unused because of padding.

Ah, good catch -- thanks for fixing this so quickly, @veeableful!

I'll leave this issue open in case you want to use it for tracking, but I think we can otherwise close it :)

**Comment by veeableful** [comment] 2021-05-03 03:51
Yes, I think we can close this too. If there's something that is still not working related to this, don't hesitate re-open the issue!

**Closed by veeableful** 2021-05-03 03:51 UTC
