### ISSUE TITLE
Possible memory leak in sdl: events: DropEvent

### ISSUE THREAD

**Issue by malashin** [veandco/go-sdl2#274] opened 2017-11-07 07:12 UTC
https://wiki.libsdl.org/SDL_DropEvent

According to docs `file` should be freed after the event.
> The file name, which should be freed with SDL_free().

I'm not sure how this is handled in Go.  Maybe we should defer C.SDL_free() before returning the event.

https://github.com/veandco/go-sdl2/blob/master/sdl/events.go
```go
case DROPFILE:
		return (*DropEvent)(unsafe.Pointer(cevent))
```

Need someone much more experienced then me to check this.

**Comment by malashin** [comment] 2017-11-08 09:09
This is actually the case. Will make a PR later.
```bash
1536.07kB of 1536.07kB total (  100%)
Dropped 13 nodes (cum <= 7.68kB)
      flat  flat%   sum%        cum   cum%
 1024.06kB 66.67% 66.67%  1024.06kB 66.67%  time.Sleep
  512.01kB 33.33%   100%   512.01kB 33.33%  github.com/veandco/go-sdl2/sdl.PollEvent.func1
         0     0%   100%   512.01kB 33.33%  github.com/macroblock/zl/ui/hal/sdl.(*THal).Event
         0     0%   100%   512.01kB 33.33%  github.com/veandco/go-sdl2/sdl.PollEvent
         0     0%   100%  1536.07kB   100%  main.main
         0     0%   100%  1536.07kB   100%  runtime.goexit
         0     0%   100%  1536.07kB   100%  runtime.main
```

**Comment by x8522207x** [comment] 2017-11-11 14:54
Hello,could you also test the following code?
I think there is also memory leak in the function.


func PollEvent() Event {
        ret := C.SDL_PollEvent(&cevent)//here memory leak
        if ret == 0 {
                return nil
        }
        return goEvent((*CEvent)(unsafe.Pointer(&cevent)))
}

**Comment by veeableful** [comment] 2017-11-11 15:38
Hi @x8522207x, could you tell me which event causes memory leak? I've merged @malashin's PR which fixes DropEvent memory leak.

**Comment by x8522207x** [comment] 2017-11-11 16:14
Hi @veeableful  I just call the "sdl.PollEvent()" function when I run a endless loop 
like the following code 
for {
sdl.PollEvent()
}
I use htop to observe the memory, I find the memory keep increasing.

**Comment by veeableful** [comment] 2017-11-11 16:29
@x8522207x, could you provide me with a working code that reproduces the issue? I ran

```
package main

import "github.com/veandco/go-sdl2/sdl"

func main() {
        for {
                sdl.PollEvent()
        }
}
```

but the memory seems to not increase. I monitored using `top` using byte units.

**Comment by x8522207x** [comment] 2017-11-11 17:05
@veeableful  really? Because I ran the same code ,the memory would increase......
or maybe there are other reasons ?

**Comment by veeableful** [comment] 2017-11-11 17:13
@x8522207x, could you tell me the commit id of go-sdl2 that you're using and the OS you are running?

**Comment by x8522207x** [comment] 2017-11-11 17:17
@veeableful  My OS is centOS 6.8 but I don't know the commit id .
I using the latest  go-sdl2.

**Comment by malashin** [comment] 2017-11-13 09:38
No memory leak on windows.

My PR only fixes the dropEvent. So you would actually need to use dropEvents it to leak memory by not freeing the pointer to the filename. Just running a PollEvent loop does not leak.

I think this issue can be closed.

**Closed** 2017-11-16 05:13 UTC
